language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-add-repository -y ppa:beineri/opt-qt502
  - sudo apt-get update -qq
  - sudo apt-get install -qq qmake qt5-meta-minimal
script:
  - qmake -project
  - qmake tests/tests.pro
  - make
branches:
  only:
    - master
notifications:
  recipients:
    - cedric.lahouste@gmail.com
  email:
    on_success: change
    on_failure: always